dev:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: ${POSTGRES_PASSWORD}
      port: 5432
      dbname: targetdb
      schema: public
