version: 1
default_environment: dev
project_id: 0198cc50-8b2f-76cc-bfad-9d05541cccf1
environments:
- name: dev
- name: staging
- name: prod
plugins:
  extractors:
  - name: tap-mssql
    variant: buzzcutnorman
    pip_url: git+https://github.com/BuzzCutNorman/tap-mssql.git
    config:
      host: localhost
      port: 1433
      user: sa
      database: testdb
      include_views: true
    select:
    - dbo-VwCustomers.*
  - name: tap-csv
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/tap-csv.git
    config:
      files:
      - entity: test_table              # Nome logico della tabella
        path: ./data.csv                # Percorso del file CSV
        keys: [id]                      # Chiave primaria (se esiste)
        delimiter: ','                  # Separatore ("," ";" "\t")
  loaders:
  - name: target-postgres
    variant: meltanolabs
    pip_url: meltanolabs-target-postgres
    config:
      host: localhost
      port: 5432
      user: postgres
      password: ${POSTGRES_PASSWORD}    # Utilizza la variabile di ambiente
      database: targetdb
      default_target_schema: public
      batch_size_rows: 10000            # Numero di righe per batch
      stream_maps:
        dbo-VwCustomers:
          __alias__: customers_staging
  transformers:
  - name: dbt
    variant: dbt-labs
    pip_url: dbt-core~=1.3.0 dbt-postgres~=1.3.0
    config:
      profiles_dir: ./dbt
      target: dev
jobs:
  - name: mssql_overwrite_postgres
    tasks:
      - dbt:run                  # esegue il TRUNCATE tramite modello dbt
      - tap-mssql target-postgres # carica i dati da MSSQL a Postgres